apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-cd
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: aws-eni
    repoURL: 'https://github.com/littlejo/argocd-cilium'
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
